export { default as AddJob } from "./AddJob/AddJob";
export { default as Admin } from "./Admin/Admin";
export { default as AllJobs } from "./AllJobs/AllJobs";
export { default as DashboardLayout } from "./DashboardLayout/DashboardLayout";
// export { default as DeleteJob } from "./DeleteJob/DeleteJob";
export { default as EditJob } from "./EditJob/EditJob";
export { default as Error } from "./Error/Error";
export { default as HomeLayout } from "./HomeLayout/HomeLayout";
export { default as Landing } from "./Landing/Landing";
export { default as Login } from "./Login/Login";
export { default as Profile } from "./Profile/Profile";
export { default as Register } from "./Register/Register";
export { default as Stats } from "./Stats/Stats";
